### ISSUE TITLE
Use noscript to alert users JS required.

### ISSUE THREAD

**Issue by wurde** [Brandon-Pampuch/Easypeasy-blog#20]
https://www.w3.org/TR/html/semantics-scripting.html#the-noscript-element

```html
<noscript>
  You need to enable JavaScript to run this app.
</noscript>
```

**Comment by secantsquared** [comment]
@wurde Was removing my sloppy console.log from the BlogPost and saw this issue so I threw in the noscript tag just since I had noticed it and was making that other commit.

❓ Requesting review for closing of issue #20
